### ISSUE TITLE
Inline component for Link

### ISSUE THREAD

**Issue by lucas-barbero** [worldline/RunningOrder#43]
In order to add a Link to a StoryInformation, we need a specific UI component similar to the actual InlineEditableListComponent.

**Comment by Neckow** [comment]
- [x] Affichage d’un lien clickable en mode lecture
- [x] Affichage de deux champs quand on clique sur edit (bouton devient done)
- [x] Action Done: Fermer les 2 champs et afficher juste le liens clickable 
- [x] Ajout du style sur le textField
- [x] Gérer le http/https
